pipeline:
  step:
    image: php:7.0-alpine
    commands:
      - php connect.php

services:
  database:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_USER=username
     - MYSQL_PASSWORD=password
