pipeline:
  parallel_1:
    image: php: docker.solutiondrive.de/repository/library/php-xdebug:7.1.3
    group: parallel
    commands:
      - php sleep.php

  parallel_2:
    image: docker.solutiondrive.de/repository/library/php-xdebug:7.1.3
    group: parallel
    commands:
      - php sleep.php

  non_parallel:
    image: docker.solutiondrive.de/repository/library/php-xdebug:7.1.3
    commands:
      - php -v
