pipeline:
  step:
    image: php:7.0-alpine
    commands:
      - php -v
      - php connect.php

services:
  database:
    image: mariadb
   environment:
     - MYSQL_USER=username
     - MYSQL_PASSWORD=password
