pipeline:
  parallel_1:
    image: library/php:7.2-cli-alpine
    group: parallel
    commands:
      - php sleep.php

  parallel_2:
    image: library/php:7.2-cli-alpine
    group: parallel
    commands:
      - php sleep.php

  non_parallel:
    image: library/php:7.2-cli-alpine
    commands:
      - php -v
