pipeline:
  step:
    image: bigtruedata/php-mysqli
    commands:
      - sleep 15
      - php connect.php

services:
  database:
    image: mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_USER=username
     - MYSQL_PASSWORD=password
