pipeline:
  parallel_1:
    image: php:${PHP_VERSION}-alpine
    group: parallel
    commands:
      - php sleep.php

  parallel_2:
    image: php:${PHP_VERSION}-alpine
    group: parallel
    commands:
      - php sleep.php

  non_parallel:
    image: php:${PHP_VERSION}-alpine
    commands:
      - php -v


matrix:
  PHP_VERSION:
    - 5.6
    - 7.0
    - 7.1
